export { IOtp } from './otp/IOtp'
export { IOtpRepository } from './otp/IOtpRepository'
export { IOtpController } from './otp/IOtpController'
export { IOtpService } from './otp/IOtpService'
export { ICreateOtp, IReadOtp } from './otp/IOtpDTO'
